- name: matlab directory
  file:
    path: /var/www/ood/apps/sys/matlab
    state: directory

- git:
    repo: 'https://github.com/OSC/bc_osc_matlab.git'
    dest: /var/www/ood/apps/sys/matlab/
    clone: yes

- name: modify to fit our environment 
  lineinfile:
    path: /var/www/ood/apps/sys/matlab/submit.yml.erb
    regexp: '^cluster:'
    line: 'cluster: {{ cluster_name }}'

- name: modify to fit our environment
  lineinfile:
    path: /var/www/ood/apps/sys/matlab/form.yml
    regexp: '^cluster:'
    line: 'cluster: {{ cluster_name }}'

- name: Restart httpd24-httpd
  service:
    name: httpd24-httpd
    state: restarted

