---
- name: Put custom cluster.yml in place
  template:
    src: cluster.yml
    dest: /etc/ood/config/apps/bc_desktop/{{ cluster_name }}.yml
    backup: yes

- name: Put submit.yml.erb in place
  copy:
    src: vnc-submit.yml.erb
    dest: /etc/ood/config/apps/bc_desktop/submit/submit.yml.erb
    backup: yes
