---
- hosts: headnode
  roles:
    - { name: 'pre_ohpc', tags: 'pre_ohpc' }
    - { name: 'ohpc_install', tags: 'ohpc_install' }
    - { name: 'ohpc_config_build', tags: 'ohpc_config' }
    - { name: 'ohpc_add_easybuild', tags: 'ohpc_add_easybuild', when: easybuild_provision | bool }
    - { name: 'ohpc_jupyter', tags: 'ohpc_jupyter', when: jupyter_provision | bool }
    - { name: 'ohpc_matlab', tags: 'ohpc_matlab', when: matlab_provision | bool }
    - { name: 'ohpc_sas', tags: 'ohpc_sas', when: sas_provision | bool }
    - { name: 'ohpc_rabbitmq', tags: 'ohpc_rabbitmq', when: enable_user_reg | bool }
    - { name: 'ohpc_add_rstudio', tags: 'ohpc_add_rstudio', when: rstudio_provision | bool }
    - { name: 'ohpc_user_reg', tags: 'ohpc_user_reg', when: enable_user_reg | bool }
    - { name: 'ohpc_add_rabbitmq_agents', tags: 'ohpc_add_rabbitmq_agents', when: enable_user_reg | bool }
    - { name: 'sshpiper', tags: 'sshpiper', when: enable_sshpiper | bool }
