---
- hosts: ood
  roles:
    - { name: 'prep_ood', tags: 'prep_ood' }
    - { name: 'ood', tags: 'ood' }
    - { name: 'warewulf_sync', tags: 'warewulf_sync' }
    - { name: 'ood_matlab', when: matlab_provision, tags: 'ood_matlab' }
    - { name: 'ood_firewall_and_services', tags: 'ood_firewall_and_services' }
    - { name: 'ohpc_firewall_and_services', tags: 'ohpc_firewall_and_services' }

