---
- name: Get OpenHPC repo
  yum: name={{ openhpc_release_rpm }} state=present update_cache=true

- name: Install Copr plugin for yum
  yum: name=yum-plugin-copr state=present update_cache=true
  when: enable_copr == true

- name: enable Copr Repos
  shell: yum -y copr enable "{{ item.repo_name }}"
  with_items: "{{ copr_repos }}"
  when: enable_copr == true and group_names | intersect(item.groups)

- name: Install dependencies-nfs-utils, ohpc packages, ntp and other required tools.
  yum: name={{ item }} state=installed update_cache=true
  with_items:
    - nfs-utils
    - ohpc-base-compute
    - ohpc-slurm-client
    - zsh
    - git
    - vim
    - tmux
    - ruby

- name: Mount /home, /opt/ohpc/pub from OHPC node
  lineinfile:
    path: /etc/fstab
    line: '{{ item }}'
  with_items:
    - "{{ headnode_private_ip }}:/home /home nfs nfsvers=3,nodev,nosuid,noatime 0 0"
    - "{{ headnode_private_ip }}:/opt/ohpc/pub /opt/ohpc/pub nfs nfsvers=3,nodev,noatime 0 0"
