---
# Implement warewulf file synchrnoization for cluster integration
# https://groups.io/g/OpenHPC-users/message/2084
# https://groups.io/g/OpenHPC-users/message/2405

# Discovery avoids having to hard code the ethernet device number
# it keys off the assigned static IP for the ood node and uses that
# to discover the ethernet device and mac address for the node
# adapted from: https://serverfault.com/a/852093

- name: install warewulf file synchronization
  copy:
    src: warewulf
    dest: /
    owner: root
    group: root

# ensure script files are executable
- file:
    path: /warewulf/bin
    recurse: true
    mode: u+x,g+x

- name: add warewulf file sync via cron
  copy:
    src: wwupdatefiles
    dest: /etc/cron.d
    owner: root
    group: root
    mode: 0640

- name: create log output dir for warewulf cron
  file:
    path: /var/log/warewulf
    state: directory
    owner: root
    group: root
    mode: 755

- name: Copy wwnodeconf from template
  template:
    src: wwnodeconf.j2
    dest: /warewulf/config
