---
- fail:
    msg: Please specify password for rabbitmq user
  when: rabbitmq_user_password == "" or celery_user_password == ""

- name: Import RabbitMQ signing key
  rpm_key:
    state: present
    key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

#- name: Add RabbitMQ repository
#  yum_repository:
#    name: github-rabbitmq-rpm
#    description: RabbitMQ (CentOS 7)
#    baseurl: https://github.com/rabbitmq/rabbitmq-server/releases 
#    gpgcheck: no
#    enabled: yes

- name: Install Erlang
  yum:
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.3.3/erlang-23.3.3-1.el7.x86_64.rpm
    state: present

- name: Install RabbitMQ Server
  yum:
    name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.16/rabbitmq-server-3.8.16-1.el7.noarch.rpm 
    state: present

- name: Start and enable RabbitMQ Server
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Add RabbitMQ user
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_user_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

# the user_reg feature makes use of celery for task managment in flask
# this requires a communication channel dedicated to celery in RabbitMQ
- name: Add Vhost in celery
  rabbitmq_vhost:
    name: "{{ celery_vhost }}"
    state: present

- name: Add User in celery
  rabbitmq_user:
    user: "{{ celery_user }}"
    password: "{{ celery_user_password }}"
    vhost: "{{ celery_vhost }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

# jpr: this may be redundant for ohpc
# also, we should know what ports to open. ;)
- name: Turn off firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
