---
  - name: Extract Slurm 17.11.11 RPMs
    unarchive:
      src: "{{ slurm_17_11_11_url }}"
      dest: "{{ slurm_17_11_11_dest }}"
      remote_src: yes

  - name: Update slurm related packages on ohpc node
    yum:
      name:
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-devel-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-example-configs-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-perlapi-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-slurmctld-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-slurmdbd-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
    when: inventory_hostname == cluster_name

  - name: Update slurm related packages for compute node image
    yum:
      installroot: "{{ compute_chroot_loc }}"
      name:
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-contribs-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-example-configs-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-pam_slurm-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-perlapi-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-slurmd-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
    when: inventory_hostname == cluster_name

  - name: Rebuild compute node vnfs image
    command: wwvnfs -y --chroot "{{ compute_chroot_loc }}/"
    when: inventory_hostname == cluster_name

  - name: Update slurm related packages on Open OnDemand node
    yum:
      name:
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-contribs-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-example-configs-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-pam_slurm-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-perlapi-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
        - "{{ slurm_17_11_11_dest }}/slurm17.11.11/slurm-slurmd-ohpc-17.11.11-6.2.ohpc.1.3.6.x86_64.rpm"
    when: inventory_hostname == ood_nodename
