- name: Create directory
  file:
    path: "{{ ansys_install_root }}/{{ item }}/bin"
    state: directory
    mode: 0755
  with_items: "{{ ansys_versions }}"

- name: Install ansys (Executable file to run  xfce4desktop)
  template:
    src: runwb2
    dest: "{{ ansys_install_root }}/{{ item }}/v191/Framework/bin/"
    mode: a+x
  with_items: "{{ ansys_versions }}"

- name: Create modules directory
  file:
    path: "{{ ansys_modulefiles_dir }}"
    state: directory
    mode: 0755

- name: Copy modulefile from template to module path
  template:
    src: 19.1
    dest: "{{ ansys_modulefiles_dir }}/{{ item }}"
  with_items: "{{ ansys_versions }}"

- name: Check if modulefiles path is in default MODULEPATH
  shell: grep "{{ cluster_shared_folder }}/modulefiles" {{ module_script }} 
  ignore_errors: yes
  register: default_modulepath_sh

- shell: grep "{{ cluster_shared_folder }}/modulefiles" {{ module_csh }}
  ignore_errors: yes
  register: default_modulepath_csh

- name: Add modulefiles path into default MODULEPATH
  replace:
    path: {{ module_script }}
    regexp: '(MODULEPATH=.*)'
    replace: '\1:{{ cluster_shared_folder }}/modulefiles'
    backup: yes
  when: default_modulepath_sh.stdout == ""

- replace:
    path: {{ module_csh }}
    regexp: '(MODULEPATH "[^"]*)'
    replace: '\1:{{ cluster_shared_folder }}/modulefiles'
    backup: yes
  when: default_modulepath_csh.stdout == ""
