- name: Create matlab directory
  file:
    path: "{{ matlab_clustershare }}"
    state: directory
    mode: 0755

- name: Create directoryi for matlab bin
  file:
    path: "{{ matlab_clustershare }}/{{ matlab_module_file }}/bin" 
    state: directory
    mode: 0755

- name: Install MATLAB (Executable file to run xfce4desktop)
  template:
    src: "{{ matlab_module_appdir }}"
    dest: "{{ matlab_clustershare }}/{{ matlab_module_file }}/bin/{{ matlab_module_appdir }}"
    mode: a+x

- name: Create modules  directory
  file:
    path: "{{ matlab_module_path }}/{{ matlab_module_appdir }}"
    state: directory
    mode: 0755

- name: Copy modulefile from template to module path
  template:
    src: "{{ matlab_module_file }}"
    dest: "{{ matlab_module_path }}/{{ matlab_module_appdir }}/{{ matlab_module_file }}"
