- name: install the latest version of libXtst
  yum:
    name: libXtst
    state: latest

- name: Download matlab
  get_url:
    url: "{{ matlab_download_url }}"
    dest: /tmp/matlab.tar.gz

- name: Un-tar downloaded MATLAB 
  command: tar -xvf /tmp/matlab.tar.gz -C "{{ matlab_clustershare }}"
