- name: ansys directory
  file:
    path: /var/www/ood/apps/sys/ansys
    state: directory

- git:
    repo: 'https://github.com/OSC/bc_osc_ansys_workbench.git'
    dest: /var/www/ood/apps/sys/ansys/
    clone: yes

- name: Replace form.yml
  template:
    src: form.yml
    dest: /var/www/ood/apps/sys/ansys/form.yml

- name: Remove form.js
  file:
    path: /var/www/ood/apps/sys/ansys/form.js
    state: absent

- name: Replace form submission template
  copy:
    src: submit.yml
    dest: /var/www/ood/apps/sys/ansys/submit.yml.erb

- name: Replace form script template
  copy:
    src: script.sh.erb 
    dest: /var/www/ood/apps/sys/ansys/template/script.sh.erb 
