---
- name: Install pip for system python and build tools
  yum:
    state: present
    name:
      - '@Development Tools'
      - python3
      - python3-pip

- name: Create user build
  user:
    name: build

- name: Create Easybuild modulefiles folder
  file:
    path: "{{ easybuild_prefix }}"
    state: directory
    owner: build
    group: build

- name: Install temporary easybuild via pip
  pip:
    name: easybuild
    virtualenv: eb_venv
    virtualenv_command: /usr/bin/python3 -m venv
    chdir: /tmp

- name: Install easybuild as module
  shell: |
      source {{ module_init_script }}
      /tmp/eb_venv/bin/eb --install-latest-eb-release --prefix {{ easybuild_prefix }}
  become_user: build

- name: Remove temporary easybuild
  file:
    state: absent
    path: /tmp/eb_venv

- name: Check if EasyBuild installation path is in default MODULEPATH
  shell: grep "{{ easybuild_prefix }}/modules/all" "{{ modulepath_file }}.sh"
  ignore_errors: yes
  register: default_modulepath_sh

- shell: grep "{{ easybuild_prefix }}/modules/all" "{{ modulepath_file }}.csh"
  ignore_errors: yes
  register: default_modulepath_csh

- name: Add EasyBuild installation path into default MODULEPATH
  replace:
    path: "{{ modulepath_file }}.sh"
    regexp: '(MODULEPATH=.*)'
    replace: '\1:{{ easybuild_prefix }}/modules/all'
    backup: yes
  when: default_modulepath_sh.stdout == ""

- name: Add EasyBuild installation path into default MODULEPATH
  replace:
    path: "{{ modulepath_file }}.csh"
    regexp: '(MODULEPATH "[^"]*)'
    replace: '\1:{{ easybuild_prefix }}/modules/all'
    backup: yes
  when: default_modulepath_csh.stdout == ""

- name: Update file in warewulf file database
  command: wwsh file sync

- name: Verify EasyBuild installation
  shell: |
      source {{ module_init_script }}
      module use "{{ easybuild_prefix }}/modules/all"
      module load EasyBuild
      eb --version

