---
- name: Create nossh group
  command: /cm/local/apps/cmd/bin/cmsh -c "group; add {{ item }}; commit"
  loop:
    with_items: "{{ ssh_deny_groups }}"

- name: Add default banner for users in deny groups
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE added group: {{ item }}"
    insertafter: "^#Banner"
    backup: yes
    block: |
      DenyGroups {{ item }}
      Match Group {{ item }}
        Banner /etc/ssh/{{ item }}-msg
        ForceCommand echo
        PasswordAuthentication no
      Match all
  loop: "{{ ssh_deny_groups }}"

- name: Copy banner msg file
  copy:
    src: "{{ item }}-msg"
    dest: "/etc/ssh/{{ item }}-msg"
    owner: root
    group: root
  loop: "{{ ssh_deny_groups }}"
