---
- name: Enable the Software Collections repository
  yum:
    name: "centos-release-scl"
    state: present

- name: Add Open OnDemand’s repository hosted by the Ohio Supercomputer Center
  yum:
    name: "https://yum.osc.edu/ondemand/1.3/ondemand-release-web-1.3-1.el7.noarch.rpm"
    state: present

- name: Install OnDemand and all of its dependencies
  yum:
    name: "ondemand"
    state: present

- name: Stage http authz file for ood
  copy:
    src: htpasswd
    dest: /opt/rh/httpd24/root/etc/httpd/.htpasswd
    owner: root
    group: root
    mode: 0644

- name: Enable http service
  systemd:
    state: started
    name: httpd24-httpd
    enabled: yes

- name: Open port http/s
  firewalld:
    service: http
    permanent: true
    state: enabled

-  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Disable SELinux Enforcement (permissive)
  selinux:
    policy: permissive
    state: permissive

- name: Set SELinux to permissive mode without reboot
  command: setenforce 0
