---
  # Implement web single sign on support using shibboleth

# Shibboleth repo config from
# https://shibboleth.net/downloads/service-provider/latest/RPMS/
- name: Add shibboleth openSUSE build service repository
  yum_repository:
    name: shibboleth
    description: Shibboleth (CentOS_7)
    mirrorlist: https://shibboleth.net/cgi-bin/mirrorlist.cgi/CentOS_7
    gpgkey: https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key
    gpgcheck: yes
    enabled: yes

# note the copr repo for shibboleth was added during node prep roles
- name: install shibboleth rpm for scl apache
  yum: name=shibboleth state=latest

# note the shibboleth rpm is not fully scl-yet so need hand correction
- name: copy shibbolth apache module into ood scl installe
  copy:
    src: /etc/httpd/conf.d/shib.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/
    remote_src: yes

- name: start shibd and enable on boot
  service:
    name: shibd
    state: started
    enabled: yes

- name: Restart service httpd, in all cases
  service:
    name: httpd24-httpd
    state: restarted
