---
- name: Ensure destination directory exists
  file:
    path: /tmp/ssh_keys
    state: directory
    mode: '0755'

- name: Download SSH host keys tar.gz from S3
  aws_s3:
    mode: get
    s3_url: "{{ s3_endpoint }}"
    bucket: "{{ ssh_host_keys_s3_bucket }}"
    object: "{{ ssh_host_keys_s3_object }}"
    dest: "/tmp/ssh_keys/{{ ssh_host_keys_s3_object }}"
    aws_access_key: "{{ lts_access_key }}"
    aws_secret_key: "{{ lts_secret_key }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Unpack SSH host keys to /etc/ssh
  unarchive:
    src: "/tmp/ssh_keys/{{ ssh_host_keys_s3_object }}"
    dest: "/etc/ssh"
    remote_src: yes

- name: Restart SSH service
  ansible.builtin.service:
    name: sshd
    state: restarted

