# This is a basic workflow to help you get started with Actions

name: Ansible lint

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install ansible and ansible-lint
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9 ansible-lint==4.2.0

    - name: Lint Ansible Playbook
      run: |
        ansible-lint -v --force-color
